{{- if .Values.autoscaling.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: semaphore-metrics-apiserver
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: semaphore-metrics-apiserver
{{- end }}
