{{- if .Values.jobs.podSpec }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "agent.podSpecName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
data:
  mainContainer: |
{{ include "agent.job.podSpec.mainContainer" . | indent 4 }}
  sidecarContainers: |
{{ toYaml .Values.jobs.podSpec.sidecarContainers | indent 4 }}
  pod: |
{{ include "agent.job.podSpec.pod" . | indent 4 }}
{{- end }}
