apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "agent.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "agent.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agent.fullname" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.agent.image }}:{{ .Values.agent.imageTag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.agent.imagePullPolicy }}
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          volumeMounts:
            - name: agent-config-volume
              mountPath: "/opt/semaphore/semaphore-agent.yml"
              readOnly: true
              subPath: semaphore-agent.yml
          resources: {{ toYaml .Values.agent.resources | nindent 12 }}
      volumes:
        - name: agent-config-volume
          secret:
            secretName: {{ include "agent.fullname" . }}
            defaultMode: 0644
            items:
            - key: semaphore-agent.yml
              path: semaphore-agent.yml
