{{- if .Values.agent.autoscaling.enabled }}
{{- if .Capabilities.APIVersions.Has "autoscaling/v2" }}
apiVersion: autoscaling/v2
{{- else }}
apiVersion: autoscaling/v2beta2
{{- end }}
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "agent.fullname" . }}
  minReplicas: {{ .Values.agent.autoscaling.min }}
  maxReplicas: {{ .Values.agent.autoscaling.max }}
  metrics:
    - type: External
      external:
        metric:
          name: jobs_queued
          selector:
            matchLabels:
              agent_type: {{ include "agent.fullname" . }}
        target:
          type: Value
          value: 1
  behavior:
    scaleDown:
      selectPolicy: Disabled
    scaleUp: {{ toYaml .Values.agent.autoscaling.scaleUp | nindent 6 }}
{{- end }}
