{{- if .Values.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "agent.fullname" . }}-down
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "agent.fullname" . }}
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  metrics:
    - type: External
      external:
        metric:
          name: occupied_agents_percentage
          # selector:
          #   matchLabels:
          #     agent_type: {{ .Values.agent_type.name }}
        target:
          type: Value
          value: 75
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 10
    scaleUp:
      selectPolicy: Disabled
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "agent.fullname" . }}-up
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "agent.fullname" . }}
  minReplicas: {{ .Values.autoscaling.min }}
  maxReplicas: {{ .Values.autoscaling.max }}
  metrics:
    - type: External
      external:
        metric:
          name: queued_jobs
          selector:
            matchLabels:
              agent_type: {{ .Values.agent_type.name }}
        target:
          type: Value
          value: 1
  behavior:
    scaleDown:
      selectPolicy: Disabled
    scaleUp:
      stabilizationWindowSeconds: 20
      selectPolicy: Max
      policies:
        - type: Pods
          value: 2
          periodSeconds: 20
        - type: Percent
          value: 100
          periodSeconds: 20
{{- end }}
