apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Values.namespace.name }}
subjects:
- kind: ServiceAccount
  name: {{ include "agent.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "agent.fullname" . }}
