{{- $endpoint := .Values.agent.endpoint | required ".Values.agent.endpoint is required." -}}
{{- $token := .Values.agent.token | required ".Values.agent.token is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.secret.labels" . | nindent 4 }}
stringData:
  endpoint: {{ $endpoint }}
  token: {{ $token }}
  semaphore-agent.yml: |
    kubernetes-executor: true
    endpoint: {{ $endpoint }}
    token: {{ $token }}
    interruption-grace-period: {{ .Values.agent.interruptionGracePeriod }}
    kubernetes-image-pull-policy: {{ .Values.agent.imagePullPolicy }}
    disconnect-after-job: false