{{- $endpoint := .Values.agent.endpoint | required ".Values.agent.endpoint is required." -}}
{{- $token := .Values.agent.token | required ".Values.agent.token is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.secret.labels" . | nindent 4 }}
stringData:
  endpoint: {{ $endpoint }}
  token: {{ $token }}
  semaphore-agent.yml: |
    name-from-env: KUBERNETES_POD_NAME
    kubernetes-executor: true
    endpoint: {{ $endpoint }}
    token: {{ $token }}
    interruption-grace-period: {{ .Values.agent.interruptionGracePeriod }}
    disconnect-after-job: false
    {{- if .Values.jobs.allowedImages }}
    kubernetes-allowed-images: {{ toYaml .Values.jobs.allowedImages | nindent 6 }}
    {{- end }}
    {{- if .Values.jobs.podSpec }}
    kubernetes-pod-spec: {{ include "agent.podSpecName" . }}
    {{- end }}
    {{- if .Values.jobs.preJobHook.enabled }}
    pre-job-hook-path: {{ .Values.jobs.preJobHook.path }}/pre-job-hook
    fail-on-pre-job-hook-error: {{ .Values.jobs.preJobHook.failOnError }}
    source-pre-job-hook: true
    {{- end }}

  {{- if .Values.jobs.preJobHook.enabled }}
  pre-job-hook: |
{{ tpl .Values.jobs.preJobHook.script . | indent 4 }}
  {{- end }}