{{- $endpoint := .Values.agent.endpoint | required ".Values.agent.endpoint is required." -}}
{{- $token := .Values.agent.token | required ".Values.agent.token is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  labels:
    {{- include "agent.secret.labels" . | nindent 4 }}
stringData:
  endpoint: {{ $endpoint }}
  token: {{ $token }}
  semaphore-agent.yml: |
    kubernetes-executor: true
    kubernetes-default-image: "{{ .Values.jobs.image }}"
    kubernetes-image-pull-policy: {{ .Values.jobs.imagePullPolicy }}
    {{- if .Values.jobs.imagePullSecrets }}
    kubernetes-image-pull-secrets: {{ toYaml .Values.jobs.imagePullSecrets | nindent 6 }}
    {{- end }}
    endpoint: {{ $endpoint }}
    token: {{ $token }}
    {{- if .Values.jobs.env }}
    env-vars: {{ toYaml .Values.jobs.env | nindent 6 }}
    {{- end }}
    interruption-grace-period: {{ .Values.agent.interruptionGracePeriod }}
    disconnect-after-job: false