{{- $endpoint := .Values.agent.endpoint | required ".Values.agent.endpoint is required." -}}
{{- $token := .Values.agent.token | required ".Values.agent.token is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agent.fullname" . }}
  namespace: {{ .Values.namespace.name }}
stringData:
  semaphore-agent.yml: |
    kubernetes-executor: true
    endpoint: {{ $endpoint }}
    token: {{ $token }}
    interruption-grace-period: {{ .Values.agent.interruptionGracePeriod }}
    kubernetes-image-pull-policy: {{ .Values.agent.imagePullPolicy }}
