apiVersion: v1
kind: Service
metadata:
  name: {{ include "metricsServer.name" . }}
  labels:
    {{- include "metricsServer.labels" . | nindent 4 }}
spec:
  ports:
    - name: https
      port: 443
      targetPort: 6443
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: {{ include "metricsServer.name" . }}
