# Default values for controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# The Semaphore API token and endpoint used by the controller to look into the job queue.
# These are the only required values for this chart.
apiToken: ""
endpoint: ""

image: semaphoreci/controller
imageTag: ""
imagePullPolicy: IfNotPresent

agent:
  image: semaphoreci/agent
  version: v2.2.14

  # TODO
  allowedImagesForJobs: []

  # By default, the controller creates a pod spec which will be used
  # if no pod spec are specified in the agent types secret.
  # The default pod spec adds a pre-job hook which installs the Semaphore toolbox.
  # See: https://github.com/semaphoreci/agent/blob/master/docs/kubernetes-executor.md#--kubernetes-pod-spec
  defaultPodSpec:
    enabled: true
    pod: {}
    mainContainer: {}
    sidecarContainers: {}
    preJobHook:
      enabled: true
      path: "/opt/semaphore/hooks"
      failOnError: true
      customScript: ""

# How many jobs the controller will keep running in parallel
parallelism: 10

nameOverride: ""
fullnameOverride: ""
resources: {}
securityContext: {}
podSecurityContext: {}
