apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "create", "delete", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "controller.fullname" . }}
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "controller.fullname" . }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "controller.fullname" . }}-agent
  labels:
    {{- include "controller.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "controller.fullname" . }}-agent
  labels:
    {{- include "controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "create", "patch", "delete"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "controller.fullname" . }}-agent
  labels:
    {{- include "controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "controller.fullname" . }}-agent
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: {{ include "controller.fullname" . }}-agent
