{{- if and (eq .Values.endpointSecret.name "") (eq .Values.endpoint "") }}
  {{- fail "Either .Values.endpoint or .Values.endpointSecret.name must be set" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
stringData:
{{- if ne .Values.endpoint "" }}
  endpoint: {{ .Values.endpoint }}
{{- end }}
{{- if and .Values.agent.defaultPodSpec.preJobHook.enabled .Values.agent.defaultPodSpec.preJobHook.customScript }}
  pre-job-hook: |
{{ .Values.agent.defaultPodSpec.preJobHook.customScript | b64dec | indent 4 }}
  {{- else if .Values.agent.defaultPodSpec.preJobHook.enabled }}
  pre-job-hook: |
{{ .Files.Get "pre-job-hook.sh" | indent 4 }}
  {{- end }}
