{{- $endpoint := .Values.endpoint | required ".Values.endpoint is required." -}}
{{- $apiToken := .Values.apiToken | required ".Values.apiToken is required." -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controller.fullname" . }}
  labels:
    {{- include "controller.labels" . | nindent 4 }}
stringData:
  endpoint: {{ $endpoint }}
  apiToken: {{ $apiToken }}
{{- if and .Values.agent.defaultPodSpec.preJobHook.enabled .Values.agent.defaultPodSpec.preJobHook.customScript }}
  pre-job-hook: |
{{ .Values.agent.defaultPodSpec.preJobHook.customScript | b64dec | indent 4 }}
  {{- else if .Values.agent.defaultPodSpec.preJobHook.enabled }}
  pre-job-hook: |
{{ .Files.Get "pre-job-hook.sh" | indent 4 }}
  {{- end }}
