# Default values for agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace:
  create: true
  name: "semaphore"

agent:
  # The Semaphore organization URL endpoint, e.g., <organization>.semaphoreci.com
  endpoint: ""

  # The Semaphore agent type registration token (required)
  token: ""

  # How long will the agent wait for a running job to finish,
  # after receiving an interruption signal from Kubernetes.
  interruptionGracePeriod: 300

  # The policy to use when pulling images specified in job YAMLs.
  imagePullPolicy: IfNotPresent

image:
  repository: semaphoreci/agent
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
