# Default values for agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override the chart name
nameOverride: ""

# Override the fully qualified app name.
fullnameOverride: ""

###########################################################
# Configuration for the pods running the Semaphore agents #
###########################################################
agent:

  # The Semaphore organization URL used to register the agents.
  # For example: <organization-name>.semaphoreci.com
  endpoint: ""

  # The Semaphore agent type registration token used to register the agents for this pool.
  token: ""

  # Controls how long the Semaphore agent waits before stopping a job
  # it is currently running when it receives an interruption signal
  # from Kubernetes (HPA scaling down the agent deployment).
  # By default, this is 1h.
  interruptionGracePeriod: 3600

  # The Docker image used to run the agents.
  image: semaphoreci/agent

  # By default, the chart appVersion is used as the image tag. This overrides that.
  imageTag: ""

  # The image pull policy used for the agent pods.
  imagePullPolicy: IfNotPresent

  # The image pull secrets used to pull the agent image.
  imagePullSecrets: []

  # Annotations to add to the agent pods.
  annotations: {}

  # Labels to add to the agent pods.
  labels: {}

  # The resources used in the agent pods.
  # The agents should work just fine with these resources,
  # but having them configured here allows us to increase them if not enough.
  resources:
    limits:
      cpu: 0.1
      memory: 50Mi
    requests:
      cpu: 0.05
      memory: 25Mi

  # The number of replicas for the agent deployment.
  # This is used if agent.autoscaling.enabled is not true.
  # If agent.autoscaling.enabled is true, agent.autoscaling.min is used instead.
  replicas: 1

  # NOTE: this requires the external-metrics-server chart to be installed.
  autoscaling:
    enabled: true
    min: 1
    max: 10

    # Controls the HPA's scaleUp behavior, and controls how fast agents are scaled up.
    # By default, we either increase the number of pods by 200% or by 10, whatever is greatest, every 30s.
    # See: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 30
      policies:
        - type: Pods
          value: 10
          periodSeconds: 30
        - type: Percent
          value: 200
          periodSeconds: 30

##############################################
# Configuration for the pods created by the  #
# Semaphore agents to run the Semaphore jobs #
##############################################
jobs:

  # List of regexes to apply on images used by jobs.
  # See: https://github.com/semaphoreci/agent/blob/master/docs/kubernetes-executor.md#restricting-images-used-in-jobs
  allowedImages: []

  # Additional configuration for the main container, sidecar containers and the pod itself.
  # See: https://github.com/semaphoreci/agent/blob/master/docs/kubernetes-executor.md#--kubernetes-pod-spec
  podSpec:
    mainContainer: {}
    sidecarContainers: {}
    pod: {}

  # The pre-job hook configuration.
  # See: https://docs.semaphoreci.com/ci-cd-environment/configure-self-hosted-agent/#pre-job-hook-path.
  # By default, this is enabled, and we use that hook to install the Semaphore toolbox.
  # If enabled, we store the script in a secret, and inject it into the pod running job for execution.
  preJobHook:
    enabled: true
    path: "/opt/semaphore/hooks"
    failOnError: true
    customScript: ""
