# Default values for agent.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Override the chart name
nameOverride: ""

# Override the fully qualified app name.
fullnameOverride: ""

###########################################################
# Configuration for the pods running the Semaphore agents #
###########################################################
agent:

  # The Semaphore organization URL used to register the agents.
  # For example: <organization-name>.semaphoreci.com
  endpoint: ""

  # The Semaphore agent type registration token used to register the agents for this pool.
  token: ""

  # Controls how long the Semaphore agent waits before stopping a job
  # it is currently running when it receives an interruption signal from Kubernetes.
  # Usually, the agent would receive an interruption signal from Kubernetes
  # when the HorizontalPodAutoscaler decides to scale down the number of agents running.
  interruptionGracePeriod: 300

  # The Docker image used to run the agents.
  image: semaphoreci/agent

  # By default, the chart appVersion is used as the image tag. This overrides that.
  imageTag: ""

  # The image pull policy used for the agent pods.
  imagePullPolicy: IfNotPresent

  # The image pull secrets used to pull the agent image.
  imagePullSecrets: []

  # Annotations to add to the agent pods.
  annotations: {}

  # Labels to add to the agent pods.
  labels: {}

  # The resources used in the agent pods.
  # The agents should work just fine with these resources,
  # but having them configured here allows us to increase them if not enough.
  resources:
    limits:
      cpu: 0.1
      memory: 50Mi
    requests:
      cpu: 0.05
      memory: 25Mi

  # NOTE: this requires the external-metrics-server chart to be installed.
  autoscaling:
    enabled: true
    min: 1
    max: 10

    # Controls the HPA's scaleUp behavior, and controls how fast agents are scaled up.
    # By default, we either double the number of pods or increase it by 2, whatever is greatest, every 30s.
    # See: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
    scaleUp:
      selectPolicy: Max
      stabilizationWindowSeconds: 60
      policies:
        - type: Pods
          value: 2
          periodSeconds: 30
        - type: Percent
          value: 100
          periodSeconds: 30

    # Controls the HPA's scaleDown behavior, and controls how fast agents are scaled down.
    # By default, we always decrease the number of agents by 1, every minute.
    # See: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
    scaleDown:
      stabilizationWindowSeconds: 60
      selectPolicy: Max
      policies:
        - type: Pods
          value: 1
          periodSeconds: 60

##############################################
# Configuration for the pods created by the  #
# Semaphore agents to run the Semaphore jobs #
##############################################
jobs:

  # List of regexes to apply on images used by jobs.
  # See: https://github.com/semaphoreci/agent/blob/master/docs/kubernetes-executor.md#restricting-images-used-in-jobs
  allowedImages: []
